### ISSUE TITLE
frontend: stop displaying pass button after receiving a pass update

### ISSUE THREAD

**Issue by j2kun** [j2kun/lonely-hearts#104]

**Comment by DanielNghiem** [comment]
The pass button needs to be hidden at various times:
- After receiving a successful pass update
- If the user unchooses one or more of the three chosen cards before passing

**Comment by j2kun** [comment]
Isn't the second one already handled? I think in general it would be safe to hide the pass button whenever a game update is received. Can you think of a reason we'd send game updates while people are passing?

**Comment by DanielNghiem** [comment]
@j2kun : The second one isn't implemented yet, but its an easy fix.  

I can think of a reason when we'd send game updates while people are passing:  Let's say at the beginning of the game, Player 1 chooses three cards to pass and clicks the pass button.  Each client should have their `state.round.playerAction` updated, so that the remaining three players know that Player 1 is waiting on them.  

However, currently the client-side `game_update` handler re-renders everything, if Player 2 had already clicked 2 cards, the update would wipe that out that selection, which we don't want.

**Comment by j2kun** [comment]
Good point. I could think of some ways to get around this, but I'm not sure it's worth it.
