### ISSUE TITLE
Simplify test_hearts

### ISSUE THREAD

**Issue by DanielNghiem** [j2kun/lonely-hearts#31]
Instead of importing fake.py into test_hearts.py, should I learn about pytest fixtures to do setup and teardown for my tests?

**Comment by j2kun** [comment]
No those things are a nightmare and I'd recommend we use them sparingly. We will need to deal with them when we have to make tests that involve the database. They are good for doing things like telling the code that's being run to use a "fake" (test) database instead of a real one, or filling said database with test data that is required globally (for example, maybe there is a special object that needs to exist for every test in order to create new users). For pure tests of logic, however, fixtures are overkill.

Let me know if you find yourself repeating code over and over again, and I can take a look to suggest ways to make it so you don't have to type as much.

If you want to get a headstart on stuff we'll need, I'd say learn about [python decorators](https://realpython.com/blog/python/primer-on-python-decorators/). Fixtures are just a fancy type of decorator anyway.
