### ISSUE TITLE
run.py:  Load arguments into socketio.run() from settings.py

### ISSUE THREAD

**Issue by DanielNghiem** [j2kun/lonely-hearts#71]
What  is the best way to load my environment variables ( or `CONFIGS` from settings.py) into the `host` and `port` variables?
`socketio.run(app, host='0.0.0.0', port=5000)`

**Comment by j2kun** [comment]
The file `hearts/settings.py` does all the loading from `.env` into python. The flow is this:

1. You run `python run.py`, 
2. In `run.py`, it runs the line `app = create_app()`
3. This function is defined in `hearts/__init__.py`, and it imports `settings.py` and then in `create_app` it runs `settings.configure(app)`. This function takes as input the Flask app object, and produces as output None (it mutates the flask app object)
4. The behavior of `settings.configure` is to attach new data to the Flask app's `config` attribute. So that configs can be accessed with `app.config['CONFIGVAR_NAME']`.

So, in particular, you can see in `settings.py` that I define four config variables, including `HOST` and `PORT`. If you want to change `run.py` to use those values instead of the hard-coded ones:

```
socketio.run(app, host=app.config['HOST'], port=app.config['PORT'])
```
